import projects1 from "@assets/projects/projects1.webp";
import projects2 from "@assets/projects/projects2.webp";
import projects3 from "@assets/projects/projects3.webp";

export const projects = [
  {
    id: "imagify",
    index: "Exhibit A",
    title: "Imagify",
    category: "AI | Full-Stack",
    year: "2024 August - 2025 May",
    role: ["Team Leader"],
    domain: "imagify-frontend-hcjw.onrender.com",
    liveUrl: "https://imagify-frontend-hcjw.onrender.com/",
    img: projects1,
    summary:
      "A full-stack AI image generation platform combining generative AI with a credit-based payment system, secure authentication, and end-to-end account management — built to feel like a real product, not a demo.",
    problem:
      "Most AI image tools either hide behind restrictive paywalls or offer a stripped-down experience with no real product workflow around them. The goal was to design and ship a complete system independently — authentication, payments, generation, and account management — as a cohesive product rather than a collection of disconnected features.",
    engineering:
      "Led the architecture and implementation of both frontend and backend: JWT-based authentication with refresh handling, MongoDB-backed user and credit-ledger management, Razorpay integration for a credit-based payment workflow, and orchestration with an external AI image-generation API. On the frontend, introduced route-based lazy loading and code splitting to cut initial JavaScript payload, and structured state management to keep credit balances and generation history in sync across sessions. As team lead, also owned task breakdown, code review, and integration between frontend and backend workstreams.",
    stack: ["React", "TypeScript", "Node.js", "MongoDB", "Tailwind CSS", "Razorpay", "JWT", "OpenAI API", "RBAC", "Render", "Rest API", "Admin Panel"],
    tags: ["AI/ML", "Full-Stack", "Payments", "Authentication", "SaaS"],
    metrics: [
      "500+ images generated by users",
      "40% faster dashboard loading through lazy loading and code splitting",
      "JWT end-to-end authentication",
      "Razorpay credit-based payment workflow",
    ],
    visualization: {
      type: "bar",
      title: "Dashboard Load Time",
      unit: "seconds",
      data: [
        { label: "Before optimization", value: 3.2 },
        { label: "After optimization", value: 1.9 },
      ],
    },
  },
  {
    id: "quready",
    index: "Exhibit B",
    title: "Quready",
    category: "Developer Tools | Education",
    year: "2024 | May - July",
    role: ["Solo Developer"],
    domain: "quready.vercel.app",
    liveUrl: "https://quready.vercel.app/",
    img: projects2,
    summary:
      "A structured DSA preparation platform built to replace scattered spreadsheets and bookmarks with a single, trackable source of truth for interview prep.",
    problem:
      "Interview preparation resources are scattered across LeetCode lists, YouTube playlists, and personal spreadsheets. Engineers lose time deciding what to solve next instead of actually solving problems, and progress tracking rarely survives switching between tools.",
    engineering:
      "Built a frontend-first experience housing 450+ categorized problems, organized by topic and difficulty, with filtering and search to reduce decision fatigue. Implemented persistent progress tracking entirely in local storage, so users get a stateful experience with zero backend, zero signup friction, and zero server cost. Designed a responsive layout so the tracker is equally usable for quick mobile check-ins and focused desktop sessions.",
    stack: ["React", "Tailwind CSS", "JavaScript", "DSA" , "Education", "Responsive Design"],
    tags: ["EdTech", "Frontend", "Client-Side Storage", "DSA", "Solo Project"],
    metrics: [
      "450+ problems indexed and categorized",
      "50+ students using the platform for interview preparation",
      "Zero backend — progress persists entirely on the client",
      "Responsive across all devices",
    ],
    visualization: {
      type: "donut",
      title: "Problems by Difficulty",
      unit: "problems",
      data: [
        { label: "Easy", value: 150 },
        { label: "Medium", value: 200 },
        { label: "Hard", value: 100 },
      ],
    },
  },
  {
    id: "sortlab",
    index: "Exhibit C",
    title: "SortLab",
    category: "Algorithms | Education | Visualization",
    year: "2024 | July - September",
    role: ["Solo Developer"],
    domain: "sorting-visualizer-rahul-goswamis-projects-c6755eb5.vercel.app",
    liveUrl: "https://sorting-visualizer-rahul-goswamis-projects-c6755eb5.vercel.app/",
    img: projects3,
    summary:
      "An interactive algorithm visualization tool that turns abstract sorting logic into real-time, watchable animation — built to make the 'aha' moment click faster than reading pseudocode ever could.",
    problem:
      "Sorting algorithms are usually taught as static code walkthroughs, which makes it hard to build intuition for what's actually happening. Understanding comparisons, swaps, and partitioning becomes dramatically easier when those operations can be seen happening step by step, at a controllable pace.",
    engineering:
      "Implemented six sorting algorithms (including Bubble, Merge, Quick, and Selection Sort) with custom animation loops driven by React state rather than CSS transitions alone, to keep visual state perfectly in sync with algorithm state. Built distinct visual states for comparisons, swaps, and finalized elements, plus controls for array size, animation speed, and step-by-step execution for granular, pause-and-inspect learning.",
    stack: ["React", "Tailwind CSS", "JavaScript", "Visualization", "Animation", "Chart.js", "Algorithms"],
    tags: ["Algorithms", "Data Visualization", "Education", "Animation", "Solo Project"],
    metrics: [
      "6 sorting algorithms visualized",
      "Real-time speed & array-size control",
      "Step-by-step animation mode",
      "Colour-coded comparison states",
    ],
    visualization: {
      type: "line",
      title: "Comparisons vs Array Size (Bubble Sort)",
      unit: "comparisons",
      data: [
        { label: "10", value: 45 },
        { label: "20", value: 190 },
        { label: "50", value: 1225 },
        { label: "100", value: 4950 },
      ],
    },
  },
];