import projects1 from "@assets/projects/projects1.webp";
import projects2 from "@assets/projects/projects2.webp";
import projects3 from "@assets/projects/projects3.webp";


export const projects = [
  {
    id: "imagify",
    index: "Exhibit A",
    title: "Imagify",
    category: "AI · Full-Stack",
    year: "2024",
    role: "Solo Developer",
    domain: "imagify-frontend-hcjw.onrender.com",
    liveUrl: "https://imagify-frontend-hcjw.onrender.com/",
    img: projects1,
    summary:
      "A full-stack AI image generation platform combining generative AI with a credit-based payment system, user authentication and account management.",
    problem:
      "Most AI image tools either hide behind restrictive paywalls or provide limited experiences without a complete product workflow. The goal was to build the entire system independently — from authentication and payments to AI generation and account management.",
    engineering:
      "Designed and implemented the frontend and backend architecture, including JWT authentication, MongoDB-backed user and credit management, Razorpay payments and integration with an AI image-generation API. On the frontend, implemented lazy loading and code splitting to reduce the amount of JavaScript required during initial application load.",
    stack: ["React", "Node.js", "MongoDB", "Tailwind CSS", "Razorpay", "JWT"],
    metrics: [
      "500+ images generated by users",
      "40% faster dashboard loading through lazy loading and code splitting",
      "JWT end-to-end authentication",
      "Razorpay credit-based payment workflow",
    ],
  },
  {
    id: "quready",
    index: "Exhibit B",
    title: "Quready",
    category: "Developer Tools · Education",
    year: "2024",
    role: "Solo Developer",
    domain: "quready.vercel.app",
    liveUrl: "https://quready.vercel.app/",
    img: projects2,
    summary:
      "A structured DSA preparation platform designed to make technical interview preparation easier to organize and track.",
    problem:
      "Interview preparation resources are scattered across multiple platforms. Engineers spend unnecessary time deciding what to solve instead of actually solving problems.",
    engineering:
      "Built a frontend-first experience containing 450+ categorized problems, organized by topic and difficulty. Implemented local-storage persistence so users could track progress without creating an account or depending on a backend. Designed the interface to remain usable across desktop and mobile devices.",
    stack: ["React", "Tailwind CSS", "JavaScript"],
    metrics: [
      "450+ problems indexed and categorized",
      "50+ students using the platform for interview preparation",
      "Zero Backend — progress persists entirely on the client",
      "Responsive across all devices",
    ],
  },
  {
    id: "sortlab",
    index: "Exhibit C",
    title: "SortLab",
    category: "Algorithms · Education · Visualization",
    year: "2024",
    role: "Solo Developer",
    domain: "sorting-visualizer-rahul-goswamis-projects-c6755eb5.vercel.app",
    liveUrl: "https://sorting-visualizer-rahul-goswamis-projects-c6755eb5.vercel.app/",
    img: projects3,
    summary:
      "An interactive algorithm visualization tool designed to make sorting algorithms understandable through real-time animation.",
    problem:
      "Sorting algorithms are often taught as static code. Understanding comparisons, swaps and partitions becomes much easier when those operations can be seen happening in real time.",
    engineering:
      "Implemented six sorting algorithms with controlled animation loops and React state management. Built visual states for comparisons, swaps and completed elements, alongside controls for array size, animation speed and step-by-step execution.",
    stack: ["React", "Tailwind CSS", "JavaScript"],
    metrics: [
      "6 sorting algorithms visualized",
      "Real-time speed & array-size control",
      "Step-by-step animation mode",
      "Colour-coded comparison states",
    ],
  },
];