import projects1 from "@assets/projects/projects1.png";
import projects2 from "@assets/projects/projects2.png";
import projects3 from "@assets/projects/projects3.png";


export const projects = [
  {
    id: "imagify",
    index: "Exhibit A",
    title: "Imagify",
    category: "AI · Full-Stack",
    year: "2024",
    role: "Solo Developer",
    domain: "imagify-frontend-hcjw.onrender.com",
    liveUrl: "https://imagify-frontend-hcjw.onrender.com/",
    img: projects1,
    summary:
      "A cloud-based platform that fuses a credit-driven billing system with generative AI image creation. Users purchase credits, generate and transform images through AI models, and manage their account — all in a single cohesive product.",
    problem:
      "Most AI image tools are either paywalled black boxes or free toys with no production-grade auth or payment flow. The goal was to build a complete, deployable product: auth, payments, AI pipeline, and a clean UI — from scratch.",
    engineering:
      "Built a full JWT authentication flow, integrated Razorpay for credit purchases, and wired the frontend to an AI image generation API. Implemented lazy loading and code-splitting to cut dashboard load time by 40%. MongoDB stores user accounts and credit ledgers.",
    stack: ["React", "Node.js", "MongoDB", "Tailwind CSS", "Razorpay", "JWT"],
    metrics: [
      "500+ images generated by users",
      "40% faster load via lazy loading & code-splitting",
      "Full auth flow with JWT + MongoDB",
      "Credit-based payment via Razorpay",
    ],
  },
  {
    id: "quready",
    index: "Exhibit B",
    title: "Quready",
    category: "Developer Tools · Frontend",
    year: "2024",
    role: "Solo Developer",
    domain: "quready.vercel.app",
    liveUrl: "https://quready.vercel.app/",
    img: projects2,
    summary:
      "A structured DSA preparation tracker for engineers preparing for technical interviews. 450+ problems indexed, categorised by topic and difficulty, with progress persisted in local storage.",
    problem:
      "Interview prep resources are scattered. Engineers waste time organising problems instead of solving them. Quready gives a single, structured sheet with progress tracking — no account required.",
    engineering:
      "Built entirely on the frontend with React and local storage persistence. Designed a filtering and categorisation system across 450+ problems. Responsive across all devices. Used by 50+ students for active interview preparation.",
    stack: ["React", "Tailwind CSS", "JavaScript"],
    metrics: [
      "450+ problems indexed & categorised",
      "Used by 50+ students for interview prep",
      "Progress tracking with local storage",
      "Responsive across all devices",
    ],
  },
  {
    id: "sortlab",
    index: "Exhibit C",
    title: "SortLab",
    category: "Education · Visualisation",
    year: "2024",
    role: "Solo Developer",
    domain: "sorting-visualizer-rahul-goswamis-projects-c6755eb5.vercel.app",
    liveUrl: "https://sorting-visualizer-rahul-goswamis-projects-c6755eb5.vercel.app/",
    img: projects3,
    summary:
      "An interactive sorting algorithm visualiser that animates Bubble, Merge, Quick, Insertion, Selection, and Heap Sort in real-time. Built to make algorithm behaviour legible through colour-coded states and step-by-step animation.",
    problem:
      "Sorting algorithms are taught abstractly. Students struggle to build intuition without seeing the comparisons, swaps, and partitions happen live. SortLab makes the invisible visible.",
    engineering:
      "Implemented six sorting algorithms with real-time animation using React state and controlled timing loops. Colour-coded comparison, swap, and sorted states. Live speed and array-size controls. Step-by-step mode for detailed inspection.",
    stack: ["React", "Tailwind CSS", "JavaScript"],
    metrics: [
      "6 sorting algorithms visualised",
      "Real-time speed & array-size control",
      "Step-by-step animation mode",
      "Colour-coded comparison states",
    ],
  },
];