import { motion } from 'framer-motion';
import { assets } from '../assets/assets';

const techBadge = (label) => (
  <span key={label} className="px-2 py-1 text-[10px] md:text-xs font-medium rounded-full bg-white/10 text-gray-300 border border-white/10">
    {label}
  </span>
);

const projects = [
  {
    title: 'Imagify',
    img: assets.projects1,
    description: 'A cloud-based platform integrating credit-driven systems with generative AI. Users can create and transform images using AI models with a seamless credit-based workflow.',
    metrics: [
      '500+ images generated by users',
      '40% faster load with lazy loading',
      'Credit-based payment via Razorpay',
      'Full auth flow with JWT + MongoDB',
    ],
    stack: ['React', 'Node.js', 'MongoDB', 'Tailwind CSS', 'Razorpay'],
    liveUrl: 'https://imagify-frontend-hcjw.onrender.com/',
  },
  {
    title: 'Quready',
    img: assets.projects2,
    description: 'A frontend web app to help users prepare for technical interviews with a structured DSA sheet. Clean UI for tracking progress across coding problems.',
    metrics: [
      '450+ problems indexed & categorized',
      'Used by 50+ students for prep',
      'Progress tracking with local storage',
      'Responsive across all devices',
    ],
    stack: ['React', 'Tailwind CSS', 'JavaScript'],
    liveUrl: 'https://quready.vercel.app/',
  },
  {
    title: 'SortLab',
    img: assets.projects3,
    description: 'An interactive sorting algorithm visualizer that animates Bubble, Merge, Quick, and more in real-time. Helps students understand algorithm behavior visually.',
    metrics: [
      'Visualizes 6+ sorting algorithms',
      'Real-time speed & size control',
      'Step-by-step animation mode',
      'Color-coded comparison states',
    ],
    stack: ['React', 'Tailwind CSS', 'JavaScript'],
    liveUrl: 'https://sorting-visualizer-rahul-goswamis-projects-c6755eb5.vercel.app/',
  },
];

function ProjectElement() {
  return (
    <div className='flex flex-col items-start justify-center gap-8 w-full'>
      
      <motion.h1 
        className="text-5xl md:text-7xl lg:text-12xl font-bold text-white text-left w-full"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 1 }}
      >
        PROJ
        <span className="text-[#353334]">ECTS</span>
      </motion.h1>

      {projects.map((project, idx) => (
        <motion.div 
          key={idx}
          className='bg-[#1C1A19] px-2 md:px-7 py-4 rounded-md flex flex-col md:flex-row justify-between items-center gap-3 md:gap-6 transition-all duration-300 cursor-pointer w-full'
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.8 }}
        >
          <motion.img 
            className='w-full md:w-96 h-auto lg:h-48 mb-4 md:mb-0 cursor-pointer pl-2 pr-2 pt-2 bg-[#F46C38] rounded-md object-fit' 
            src={project.img} 
            alt={project.title} 
          />
          
          <div className='flex flex-col items-start'>
            <motion.h1 
              className='text-xl md:text-2xl font-semibold text-left'
              initial={{ x: -100 }}
              animate={{ x: 0 }}
              transition={{ duration: 0.5 }}
            >
              {project.title}
            </motion.h1>

            <div className='flex flex-wrap gap-1.5 mt-2'>
              {project.stack.map(techBadge)}
            </div>
            
            <motion.p 
              className='mt-3 text-xs md:text-sm text-gray-300'
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.3, duration: 0.6 }}
            >
              {project.description}
            </motion.p>

            {/* Impact Metrics — listed */}
            <ul className='mt-3 flex flex-col gap-1'>
              {project.metrics.map((m, i) => (
                <li key={i} className='text-xs md:text-sm text-[#C5FF41] font-medium flex items-start gap-2'>
                  <img width={12} className='mt-0.5 shrink-0' style={{filter: 'brightness(0) invert(0.7)'}} src={assets.star} alt="•" />
                  {m}
                </li>
              ))}
            </ul>
            
            <div className='flex items-center w-full mt-4'>
              <a 
                className='text-xs md:text-sm flex items-center justify-center gap-2 rounded-md px-5 py-2 text-black bg-[#ffffffe1] hover:bg-[#ffffff44] hover:text-white font-medium transition-all duration-500' 
                href={project.liveUrl}
                target='_blank' 
                rel="noopener noreferrer"
              >
                Live Demo
                <img width={20} src={assets.arrow_right_up} alt="arrow_right_up" />
              </a>
            </div>
          </div>
        </motion.div>
      ))}
    </div>
  );
}

export default ProjectElement;
