// src/data.js — single source of truth for all portfolio content

import projects1 from "./assets/projects/projects1.png";
import projects2 from "./assets/projects/projects2.png";
import projects3 from "./assets/projects/projects3.png";
import profilePic from "./assets/jpeg/profile_pic.jpg";
import cv from "./assets/cv.pdf";

export { profilePic, cv };

// ─── PROJECTS ────────────────────────────────────────────────────────────────
export const projects = [
  {
    id: "imagify",
    index: "01",
    title: "Imagify",
    category: "AI · Full-Stack",
    year: "2024",
    role: "Solo Developer",
    domain: "imagify-frontend-hcjw.onrender.com",
    liveUrl: "https://imagify-frontend-hcjw.onrender.com/",
    img: projects1,
    summary:
      "A cloud-based platform that fuses a credit-driven billing system with generative AI image creation. Users purchase credits, generate and transform images through AI models, and manage their account — all in a single cohesive product.",
    problem:
      "Most AI image tools are either paywalled black boxes or free toys with no production-grade auth or payment flow. The goal was to build a complete, deployable product: auth, payments, AI pipeline, and a clean UI — from scratch.",
    engineering:
      "Built a full JWT authentication flow, integrated Razorpay for credit purchases, and wired the frontend to an AI image generation API. Implemented lazy loading and code-splitting to cut dashboard load time by 40%. MongoDB stores user accounts and credit ledgers.",
    stack: ["React", "Node.js", "MongoDB", "Tailwind CSS", "Razorpay", "JWT"],
    metrics: [
      "500+ images generated by users",
      "40% faster load via lazy loading & code-splitting",
      "Full auth flow with JWT + MongoDB",
      "Credit-based payment via Razorpay",
    ],
  },
  {
    id: "quready",
    index: "02",
    title: "Quready",
    category: "Developer Tools · Frontend",
    year: "2024",
    role: "Solo Developer",
    domain: "quready.vercel.app",
    liveUrl: "https://quready.vercel.app/",
    img: projects2,
    summary:
      "A structured DSA preparation tracker for engineers preparing for technical interviews. 450+ problems indexed, categorised by topic and difficulty, with progress persisted in local storage.",
    problem:
      "Interview prep resources are scattered. Engineers waste time organising problems instead of solving them. Quready gives a single, structured sheet with progress tracking — no account required.",
    engineering:
      "Built entirely on the frontend with React and local storage persistence. Designed a filtering and categorisation system across 450+ problems. Responsive across all devices. Used by 50+ students for active interview preparation.",
    stack: ["React", "Tailwind CSS", "JavaScript"],
    metrics: [
      "450+ problems indexed & categorised",
      "Used by 50+ students for interview prep",
      "Progress tracking with local storage",
      "Responsive across all devices",
    ],
  },
  {
    id: "sortlab",
    index: "03",
    title: "SortLab",
    category: "Education · Visualisation",
    year: "2024",
    role: "Solo Developer",
    domain: "sorting-visualizer-rahul-goswamis-projects-c6755eb5.vercel.app",
    liveUrl: "https://sorting-visualizer-rahul-goswamis-projects-c6755eb5.vercel.app/",
    img: projects3,
    summary:
      "An interactive sorting algorithm visualiser that animates Bubble, Merge, Quick, Insertion, Selection, and Heap Sort in real-time. Built to make algorithm behaviour legible through colour-coded states and step-by-step animation.",
    problem:
      "Sorting algorithms are taught abstractly. Students struggle to build intuition without seeing the comparisons, swaps, and partitions happen live. SortLab makes the invisible visible.",
    engineering:
      "Implemented six sorting algorithms with real-time animation using React state and controlled timing loops. Colour-coded comparison, swap, and sorted states. Live speed and array-size controls. Step-by-step mode for detailed inspection.",
    stack: ["React", "Tailwind CSS", "JavaScript"],
    metrics: [
      "6 sorting algorithms visualised",
      "Real-time speed & array-size control",
      "Step-by-step animation mode",
      "Colour-coded comparison states",
    ],
  },
];

// ─── STACK ────────────────────────────────────────────────────────────────────
export const stackEntries = [
  { name: "React.js",        code: "RCT",  category: "Frontend",          status: "Daily",       level: "primary" },
  { name: "TypeScript",      code: "TS",   category: "Frontend",          status: "Daily",       level: "primary" },
  { name: "Tailwind CSS",    code: "TWD",  category: "Frontend",          status: "Daily",       level: "primary" },
  { name: "Next.js",         code: "NXT",  category: "Frontend",          status: "In projects", level: "comfortable" },
  { name: "Ant Design",      code: "AND",  category: "Frontend",          status: "Daily",       level: "comfortable" },
  { name: "Material UI",     code: "MUI",  category: "Frontend",          status: "In projects", level: "comfortable" },
  { name: "Redux Toolkit",   code: "RTK",  category: "State",             status: "In projects", level: "comfortable" },
  { name: "TanStack Query",  code: "TSQ",  category: "State",             status: "In projects", level: "comfortable" },
  { name: "Jest / RTL",      code: "TST",  category: "Testing",           status: "In projects", level: "comfortable" },
  { name: "Framer Motion",   code: "FRM",  category: "Animation",         status: "In projects", level: "comfortable" },
  { name: "GSAP",            code: "GSP",  category: "Animation",         status: "In projects", level: "comfortable" },
  { name: "TipTap",          code: "TPT",  category: "Frontend",          status: "In projects", level: "comfortable" },
  { name: "Recharts",        code: "RCH",  category: "Frontend",          status: "In projects", level: "comfortable" },
  { name: "Node.js",         code: "NOD",  category: "Backend",           status: "In projects", level: "trace" },
  { name: "MongoDB",         code: "MDB",  category: "Database",          status: "In projects", level: "trace" },
  { name: "MySQL",           code: "SQL",  category: "Database",          status: "In projects", level: "trace" },
  { name: "Git / GitHub",    code: "GIT",  category: "Tools",             status: "Daily",       level: "primary" },
  { name: "Figma",           code: "FGM",  category: "Design",            status: "In projects", level: "comfortable" },
  { name: "Postman",         code: "PST",  category: "Tools",             status: "In projects", level: "comfortable" },
  { name: "Jira",            code: "JRA",  category: "Tools",             status: "Daily",       level: "comfortable" },
  { name: "Forgejo",         code: "FGJ",  category: "Tools",             status: "Daily",       level: "comfortable" },
  { name: "Vercel",          code: "VCL",  category: "Deployment",        status: "In projects", level: "comfortable" },
  { name: "React Native",    code: "RNT",  category: "Mobile",            status: "Learning",    level: "trace" },
];

// ─── CAREER ───────────────────────────────────────────────────────────────────
export const careerEntries = [
  {
    dateRange: "Jun 2025 — Present",
    role: "Junior Software Engineer",
    company: "Mintifi",
    companyUrl: "https://mintifi.com/",
    location: "Mumbai, India",
    type: "Full-time",
    description:
      "Building scalable fintech products used by 1,00,000+ active customers. Shipped 10+ reusable React components across customer onboarding and loan management workflows. Delivered a greenfield contract-management platform now adopted by 7+ business teams processing 100+ financial documents per month.",
    contributions: [
      "Reduced dashboard load time by 30% via memoisation, code-splitting, and lazy loading",
      "Engineered 4 finance-configurable loan-offer modules with dynamic eligibility logic",
      "Built General & Life Insurance module for in-journey sales across all loan products",
      "Shipped QR-based invoice scanning and dual-factor (Security Q&A + TOTP) authentication",
      "Migrated legacy Customer 360 management to a structured, auditable RBAC system",
    ],
    stack: ["React", "TypeScript", "Tailwind CSS", "Ant Design", "TanStack Query", "Redux Toolkit", "Jest", "Forgejo", "Jira"],
  },
  {
    dateRange: "Oct 2024 — Nov 2024",
    role: "Open Source Contributor",
    company: "GirlScript Summer of Code (GSSOC-Extd)",
    companyUrl: "https://drive.google.com/file/d/1O1aFAY6CQt1awOZcAInvY_dErQgmFhlW/view",
    location: "Remote",
    type: "Open Source",
    description:
      "Completed the extended edition of GirlScript Summer of Code as a contributor, earning six badges across multiple open-source repositories. Contributed bug fixes, feature additions, and documentation improvements.",
    contributions: [
      "6 badges earned across contribution levels",
      "Bug fixes, features, and documentation across community repos",
    ],
    stack: ["React", "JavaScript", "Open Source"],
  },
  {
    dateRange: "Oct 2024",
    role: "Hacktoberfest Contributor",
    company: "Hacktoberfest 2024",
    companyUrl: "https://www.holopin.io/@goswami2001#badges",
    location: "Remote",
    type: "Open Source",
    description:
      "Cleared all four contribution levels in Hacktoberfest 2024 — four pull requests merged across open-source projects, all four digital badges collected.",
    contributions: ["All 4 contribution levels cleared", "4 PRs merged across open-source projects"],
    stack: ["JavaScript", "Open Source"],
  },
  {
    dateRange: "Aug 2022 — Jun 2025",
    role: "B.Tech — Information Technology",
    company: "Bankura Unnayani Institute of Engineering",
    companyUrl: "https://www.buie.ac.in/",
    location: "Bankura, West Bengal",
    type: "Education",
    description:
      "Graduated with a CGPA of 8.29/10. Coursework: Data Structures & Algorithms, Database Management, Operating Systems, Computer Networks, Web Development. Gold Medalist in college sports (Long Jump, Volleyball).",
    contributions: [
      "CGPA 8.29 / 10",
      "Gold Medalist — Long Jump & Volleyball",
      "Active open-source contributor throughout degree",
    ],
    stack: ["DSA", "DBMS", "OS", "Networks", "Web Development"],
  },
];

// ─── CONTACT ──────────────────────────────────────────────────────────────────
export const contact = {
  email: "goswami.rahul1002@gmail.com",
  github: "https://github.com/RahulScripted",
  linkedin: "https://www.linkedin.com/in/rahul-goswami-ba2b51232/",
  location: "Mumbai, India",
  timezone: "IST (UTC +5:30)",
  availability: "Open to full-time roles",
};

// ─── NAV ──────────────────────────────────────────────────────────────────────
export const navLinks = [
  { label: "Work",    href: "#work" },
  { label: "Stack",   href: "#stack" },
  { label: "Career",  href: "#career" },
  { label: "Contact", href: "#contact" },
];
