export const nodes = [
  { id: "react",   name: "React",         code: "RCT", badge: "PRIMARY TOOL", icon: "https://cdn.simpleicons.org/react/61DAFB",        pos: { left: "13%", top: "23%" }, r: "-3deg", note: "Core UI library. Used across every dashboard and storefront I've shipped — the one constant." },
  { id: "next",    name: "Next.js",        code: "NXT", badge: "PRIMARY TOOL", icon: "https://cdn.simpleicons.org/nextdotjs/16140F",     pos: { left: "28%", top: "16%" }, r: "2deg",  note: "App routing, SSR, and API routes. Backbone of every production build I own end to end." },
  { id: "ts",      name: "TypeScript",     code: "TS",  badge: "CORE",         icon: "https://cdn.simpleicons.org/typescript/3178C6",   pos: { left: "45%", top: "18%" }, r: "-2deg", note: "Typed everything after one too many runtime surprises made it into production." },
  { id: "tw",      name: "Tailwind CSS",   code: "TWX", badge: "UI",           icon: "https://cdn.simpleicons.org/tailwindcss/06B6D4",  pos: { left: "64%", top: "16%" }, r: "3deg",  note: "Utility-first styling. Fastest path from a design file to pixel-accurate markup." },
  { id: "redux",   name: "Redux Toolkit",  code: "RTK", badge: "STATE",        icon: "https://cdn.simpleicons.org/redux/764ABC",        pos: { left: "82%", top: "28%" }, r: "-4deg", note: "Brought in the moment app state outgrew useState and Context — worth the boilerplate." },
  { id: "rn",      name: "React Native",   code: "RNX", badge: "MOBILE",       icon: "https://cdn.simpleicons.org/react/61DAFB",        pos: { left: "16%", top: "51%" }, r: "3deg",  note: "Cross-platform mobile. Reused most of the web app's logic to ship iOS and Android together." },
  { id: "query",   name: "TanStack Query", code: "TSQ", badge: "DATA",         icon: "https://cdn.simpleicons.org/reactquery/FF4154",   pos: { left: "32%", top: "61%" }, r: "-3deg", note: "Handles caching, refetching, and sync for anything that talks to a server." },
  { id: "node",    name: "Node.js",        code: "NOD", badge: "SERVER",       icon: "https://cdn.simpleicons.org/nodedotjs/5FA04E",    pos: { left: "68%", top: "56%" }, r: "2deg",  note: "Runtime behind every API this stack calls. Where the backend actually lives." },
  { id: "mongo",   name: "MongoDB",        code: "MDB", badge: "DATA",         icon: "https://cdn.simpleicons.org/mongodb/47A248",      pos: { left: "84%", top: "70%" }, r: "-3deg", note: "Flexible schema for early-stage products that are still finding their shape." },
  { id: "express", name: "Express.js",     code: "EXP", badge: "API",          icon: "https://cdn.simpleicons.org/express/16140F",      pos: { left: "47%", top: "82%" }, r: "4deg",  note: "Lightweight routing layer for REST endpoints — no more than the project needs." },
  { id: "gsap",    name: "GSAP",           code: "GSP", badge: "MOTION",       icon: "https://cdn.simpleicons.org/gsap/88CE02",         pos: { left: "22%", top: "83%" }, r: "-4deg", note: "Animation engine for anything Framer Motion can't handle — timelines, scroll triggers." },
  { id: "github",  name: "GitHub",         code: "GIT", badge: "SHIP",         icon: "https://cdn.simpleicons.org/github/16140F",       pos: { left: "73%", top: "86%" }, r: "3deg",  note: "Every project lives here. CI, code review, and the paper trail of every decision." },
];
